# -*- coding: utf-8 -*-
"""Deep Learning LAB Assignment 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CPIl9Ur3JQbVpFaBOJxqRrwuwwy7_Daq

Name: Anushka Gupta
Class: CSAI-A (TY)
Roll No.: 06
Batch: 3
PRN: 12311317
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score


df = pd.read_csv("house_prices.csv")

print("First 5 rows of dataset:\n", df.head())
print("\nMissing values before preprocessing:\n", df.isnull().sum())

# =========================
# 2. DATA PREPROCESSING
# =========================

# Handle missing values
df.fillna(df.mean(numeric_only=True), inplace=True)

print("\nMissing values after preprocessing:\n", df.isnull().sum())

# ==================================================
#  SIMPLE LINEAR REGRESSION (Area -> Price)
# ==================================================


X_simple = df[['Area']]
y = df['Price']


X_train, X_test, y_train, y_test = train_test_split(
    X_simple, y, test_size=0.2, random_state=42
)


scaler_simple = StandardScaler()
X_train_scaled = scaler_simple.fit_transform(X_train)
X_test_scaled = scaler_simple.transform(X_test)


simple_model = LinearRegression()
simple_model.fit(X_train_scaled, y_train)


y_pred_simple = simple_model.predict(X_test_scaled)


mse_simple = mean_squared_error(y_test, y_pred_simple)
rmse_simple = np.sqrt(mse_simple)
r2_simple = r2_score(y_test, y_pred_simple)

print("\n----- Simple Linear Regression Results -----")
print("MSE :", mse_simple)
print("RMSE:", rmse_simple)
print("R²  :", r2_simple)

# Visualization (Regression line)
plt.scatter(X_test, y_test, color='blue', label='Actual Prices')
plt.scatter(X_test, y_pred_simple, color='red', label='Predicted Prices')

sorted_idx = np.argsort(X_test.values.flatten())
plt.plot(X_test.values.flatten()[sorted_idx],
         y_pred_simple[sorted_idx],
         color='green', linewidth=2, label='Regression Line')

plt.title("Simple Linear Regression: Area vs Price")
plt.xlabel("Area")
plt.ylabel("Price")
plt.legend()
plt.show()

# ==================================================
#  MULTIPLE LINEAR REGRESSION
# (Area, Bedrooms, Age -> Price)
# ==================================================


X_multi = df[['Area', 'Bedrooms', 'Age']]
y = df['Price']


X_train, X_test, y_train, y_test = train_test_split(
    X_multi, y, test_size=0.2, random_state=42
)


scaler_multi = StandardScaler()
X_train_scaled = scaler_multi.fit_transform(X_train)
X_test_scaled = scaler_multi.transform(X_test)


multi_model = LinearRegression()
multi_model.fit(X_train_scaled, y_train)


y_pred_multi = multi_model.predict(X_test_scaled)


mse_multi = mean_squared_error(y_test, y_pred_multi)
rmse_multi = np.sqrt(mse_multi)
r2_multi = r2_score(y_test, y_pred_multi)

print("\n----- Multiple Linear Regression Results -----")
print("MSE :", mse_multi)
print("RMSE:", rmse_multi)
print("R²  :", r2_multi)

# Visualization (Actual vs Predicted)
plt.scatter(y_test, y_pred_multi)
plt.title("Multiple Linear Regression: Actual vs Predicted")
plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")
plt.show()

# =========================
# FINAL COMPARISON
# =========================
print("\n========== MODEL COMPARISON ==========")
print("Simple LR   -> MSE:", mse_simple, "RMSE:", rmse_simple, "R²:", r2_simple)
print("Multiple LR -> MSE:", mse_multi, "RMSE:", rmse_multi, "R²:", r2_multi)