# -*- coding: utf-8 -*-
"""Deep Learning LAB Assignment 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JhM4oorogPWz4FEW_goCL0dSMyvdAkb5

Name: Anushka Gupta
Class: TY CSAI-A
Roll No.: 6
Batch: 3
PRN: 12311317
"""

# ====================================================================
# Assignment No. 1: Perform PCA in dimension reduction of numerical data
# ====================================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA


from sklearn.datasets import load_iris
data = load_iris()
X = pd.DataFrame(data.data, columns=data.feature_names)
y = data.target

print("Original Data Shape:", X.shape)
print(X.head())

# ------------------------------------------
#  Data Standardization
# ------------------------------------------

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("\nStandardized Data (first 5 rows):")
print(X_scaled[:5])

# ------------------------------------------
# Perform PCA to Reduce Dimension
# ------------------------------------------

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

print("\nReduced Data Shape:", X_pca.shape)
print("Explained Variance Ratio:", pca.explained_variance_ratio_)

# ------------------------------------------
# Construct Scree Plot
# ------------------------------------------

pca_full = PCA()
X_pca_full = pca_full.fit_transform(X_scaled)

plt.figure()
plt.plot(range(1, len(pca_full.explained_variance_ratio_) + 1),
         pca_full.explained_variance_ratio_,
         marker='o')
plt.xlabel("Principal Component")
plt.ylabel("Explained Variance Ratio")
plt.title("Scree Plot")
plt.grid()
plt.show()

# ------------------------------------------
# Data Visualization in Lower Dimension
# ------------------------------------------

plt.figure()
plt.scatter(X_pca[:, 0], X_pca[:, 1], c=y)
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.title("PCA: 2D Visualization")
plt.colorbar(label="Class Label")
plt.grid()
plt.show()