# -*- coding: utf-8 -*-
"""DL Assignment 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1esgVILkaRo0ScKtbslkPpVoTb-tPPLcc

DL LAB ASSIGNMENT 5

Name: Anushka Gupta
Class: CSAI-A TY
Batch: 03
Roll No.: 6
"""

pip install pandas numpy scikit-learn matplotlib

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import mean_squared_error, r2_score

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.datasets import load_iris

data = load_iris()

X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

dt_classifier = DecisionTreeClassifier(random_state=42)

dt_classifier.fit(X_train, y_train)

y_train_pred = dt_classifier.predict(X_train)
y_test_pred = dt_classifier.predict(X_test)

print("Training Accuracy:", accuracy_score(y_train, y_train_pred))
print("Test Accuracy:", accuracy_score(y_test, y_test_pred))

print(classification_report(y_test, y_test_pred))

plt.figure(figsize=(12,8))

plot_tree(
    dt_classifier,
    filled=True,
    feature_names=data.feature_names,
    class_names=data.target_names
)

plt.show()

path = dt_classifier.cost_complexity_pruning_path(X_train, y_train)
ccp_alphas = path.ccp_alphas

trees = []

for alpha in ccp_alphas:
    tree = DecisionTreeClassifier(random_state=42, ccp_alpha=alpha)
    tree.fit(X_train, y_train)
    trees.append(tree)

train_scores = [accuracy_score(y_train, t.predict(X_train)) for t in trees]
test_scores = [accuracy_score(y_test, t.predict(X_test)) for t in trees]

plt.plot(ccp_alphas, train_scores, label="Train Accuracy")
plt.plot(ccp_alphas, test_scores, label="Test Accuracy")
plt.xlabel("Alpha")
plt.ylabel("Accuracy")
plt.legend()
plt.show()

pruned_tree = DecisionTreeClassifier(ccp_alpha=0.01)
pruned_tree.fit(X_train, y_train)

print("Pruned Tree Accuracy:",
      accuracy_score(y_test, pruned_tree.predict(X_test)))

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

rf_predictions = rf_model.predict(X_test)

print("Random Forest Accuracy:",
      accuracy_score(y_test, rf_predictions))

stump = DecisionTreeClassifier(max_depth=1)

ada_model = AdaBoostClassifier(
    estimator=stump,
    n_estimators=50,
    random_state=42
)

ada_model.fit(X_train, y_train)

ada_predictions = ada_model.predict(X_test)

print("AdaBoost Accuracy:",
      accuracy_score(y_test, ada_predictions))

from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()

X = housing.data
y = housing.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

dt_regressor = DecisionTreeRegressor(random_state=42)

dt_regressor.fit(X_train, y_train)

y_pred = dt_regressor.predict(X_test)

print("Mean Squared Error:",
      mean_squared_error(y_test, y_pred))

print("R2 Score:",
      r2_score(y_test, y_pred))

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Re-load Iris data to get the correct test set for these classification models
iris_data = load_iris()
iris_X = iris_data.data
iris_y = iris_data.target

# Re-split Iris data to get the original X_test and y_test for classification evaluation
_, X_test_iris, _, y_test_iris = train_test_split(
    iris_X, iris_y, test_size=0.3, random_state=42
)

# Decision Tree accuracy
dt_accuracy = accuracy_score(y_test_iris, dt_classifier.predict(X_test_iris))

# Pruned Decision Tree accuracy
pruned_accuracy = accuracy_score(y_test_iris, pruned_tree.predict(X_test_iris))

# Random Forest accuracy
rf_accuracy = accuracy_score(y_test_iris, rf_model.predict(X_test_iris))

# AdaBoost accuracy
ada_accuracy = accuracy_score(y_test_iris, ada_model.predict(X_test_iris))

print("Decision Tree Accuracy:", dt_accuracy)
print("Pruned Decision Tree Accuracy:", pruned_accuracy)
print("Random Forest Accuracy:", rf_accuracy)
print("AdaBoost Accuracy:", ada_accuracy)

import pandas as pd

comparison = pd.DataFrame({
    "Model": [
        "Decision Tree",
        "Pruned Decision Tree",
        "Random Forest",
        "AdaBoost"
    ],
    "Accuracy": [
        dt_accuracy,
        pruned_accuracy,
        rf_accuracy,
        ada_accuracy
    ]
})

print(comparison)

import matplotlib.pyplot as plt

models = comparison["Model"]
accuracy = comparison["Accuracy"]

plt.figure(figsize=(8,5))
plt.bar(models, accuracy)

plt.xlabel("Models")
plt.ylabel("Accuracy")
plt.title("Comparison of Models")

plt.show()

dt_classifier = DecisionTreeClassifier(max_depth=3, random_state=42)

rf_model = RandomForestClassifier(
    n_estimators=50,
    max_depth=3,
    random_state=42
)

stump = DecisionTreeClassifier(max_depth=1)

ada_model = AdaBoostClassifier(
    estimator=stump,
    n_estimators=30,
    random_state=42
)

from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris

# Load the Iris dataset again for classification cross-validation
iris_data = load_iris()
iris_X = iris_data.data
iris_y = iris_data.target

# Use iris_X and iris_y for classification models
dt_score = cross_val_score(dt_classifier, iris_X, iris_y, cv=5).mean()
rf_score = cross_val_score(rf_model, iris_X, iris_y, cv=5).mean()
ada_score = cross_val_score(ada_model, iris_X, iris_y, cv=5).mean()

print("Decision Tree CV Accuracy:", dt_score)
print("Random Forest CV Accuracy:", rf_score)
print("AdaBoost CV Accuracy:", ada_score)