# -*- coding: utf-8 -*-
"""DL LAB ASSIGNMENT 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17J6InvIgXLfxZq6SZ2osVNFGQOhxhlNC

Name: Anushka Gupta
Class: CSAI-A TY
Batch: 3
Roll No.: 06
PRN: 12311317
Assignment 8
"""

# =========================
# 1. Import Libraries
# =========================
import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
import numpy as np

# =========================
# 2. Load Dataset
# =========================
fashion_mnist = tf.keras.datasets.fashion_mnist
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

# Class labels
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress',
               'Coat', 'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

# =========================
# 3.  Colorized Images
# =========================
plt.figure(figsize=(8,8))
for i in range(9):
    plt.subplot(3,3,i+1)
    plt.imshow(x_train[i], cmap='viridis')
    plt.title(class_names[y_train[i]])
    plt.axis('off')
plt.suptitle("Colorized Fashion MNIST Samples")
plt.show()

# =========================
# 4. Preprocessing
# =========================
# Normalize
x_train = x_train / 255.0
x_test = x_test / 255.0

# Convert grayscale → RGB (3 channels)
x_train = np.stack((x_train,)*3, axis=-1)
x_test = np.stack((x_test,)*3, axis=-1)

print("Shape after RGB conversion:", x_train.shape)

# =========================
# 5. Build CNN Model
# =========================
model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(28,28,3)),
    layers.BatchNormalization(),
    layers.MaxPooling2D((2,2)),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.BatchNormalization(),
    layers.MaxPooling2D((2,2)),

    layers.Conv2D(128, (3,3), activation='relu'),
    layers.BatchNormalization(),

    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),

    layers.Dense(10, activation='softmax')
])

# =========================
# 6. Compile Model
# =========================
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

# =========================
# 7. Train Model
# =========================
history = model.fit(
    x_train, y_train,
    epochs=10,
    batch_size=64,
    validation_data=(x_test, y_test)
)

# =========================
# 8. Evaluate Model
# =========================
test_loss, test_acc = model.evaluate(x_test, y_test)
print("\nTest Accuracy:", test_acc)

# =========================
# 9. Plot Accuracy Graph
# =========================
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend(['Train', 'Validation'])
plt.show()

# =========================
# 10. Prediction Example
# =========================
predictions = model.predict(x_test)

plt.imshow(x_test[0])
plt.title("Predicted: " + class_names[np.argmax(predictions[0])])
plt.axis('off')
plt.show()