# -*- coding: utf-8 -*-
"""DL LAB Assignment 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aGKz5Ry0FJubU2r21vPsmT-g1gyD3Ak1
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier


data = pd.read_csv("iris (1).csv")


X = data.drop("species", axis=1)
y = data["species"]


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)


knn = KNeighborsClassifier(n_neighbors=3)


knn.fit(X_train, y_train)


y_pred = knn.predict(X_test)


print("Correct Predictions:")
for actual, predicted in zip(y_test, y_pred):
    if actual == predicted:
        print(f"Actual: {actual} | Predicted: {predicted}")


print("\nWrong Predictions:")
for actual, predicted in zip(y_test, y_pred):
    if actual != predicted:
        print(f"Actual: {actual} | Predicted: {predicted}")


accuracy = knn.score(X_test, y_test)
print("\nAccuracy of k-NN classifier:", accuracy)