# -*- coding: utf-8 -*-
"""DL LAB ASSIGNMENT 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VkXEXWzNN-rXxIzOnmM_USjVccd5Wi0M

DL LAB ASSIGNMENT 4

Name: Anushka Gupta
Class: CSAI-A TY
Batch: 03
Roll No.: 6
"""

import math

data = [
    {"breaking":1, "shocking":1, "exclusive":1, "label":"Fake"},
    {"breaking":1, "shocking":1, "exclusive":0, "label":"Fake"},
    {"breaking":0, "shocking":1, "exclusive":1, "label":"Fake"},
    {"breaking":0, "shocking":0, "exclusive":1, "label":"Real"},
    {"breaking":0, "shocking":0, "exclusive":0, "label":"Real"}
]

vocab = ["breaking", "shocking", "exclusive"]
classes = ["Fake", "Real"]

total_docs = len(data)
class_counts = {}

for c in classes:
    class_counts[c] = sum(1 for d in data if d["label"] == c)

priors = {c: class_counts[c]/total_docs for c in classes}

print("1️⃣ Prior Probabilities:")
for c in priors:
    print(f"P({c}) = {class_counts[c]}/{total_docs} = {priors[c]}")
print()

word_counts = {c:{word:0 for word in vocab} for c in classes}
total_words = {c:0 for c in classes}

for d in data:
    label = d["label"]
    for word in vocab:
        word_counts[label][word] += d[word]
        total_words[label] += d[word]

print("2️⃣ Word Count per Class:")
for c in classes:
    print(f"\nClass: {c}")
    for word in vocab:
        print(f"{word}: {word_counts[c][word]}")
    print(f"Total words in {c}: {total_words[c]}")
print()

likelihood = {c:{} for c in classes}
V = len(vocab)

for c in classes:
    for word in vocab:
        likelihood[c][word] = (word_counts[c][word] + 1) / (total_words[c] + V)

print("3️⃣ Likelihood Values (Laplace Smoothed):")
for c in classes:
    print(f"\nClass: {c}")
    for word in vocab:
        print(f"P({word}|{c}) = {likelihood[c][word]}")
print()

def predict(test_input):
    print("\n4️⃣ Testing News:", test_input)
    results = {}

    for c in classes:
        prob = priors[c]   # start with prior
        formula = f"P({c}|News) = P({c})"

        for word in vocab:
            count = test_input.get(word, 0)
            if count > 0:
                prob *= (likelihood[c][word] ** count)
                formula += f" * P({word}|{c})^{count}"

        results[c] = prob

        print("\nFormula:")
        print(formula)
        print("Numerical Substitution:")
        print(f"P({c}) = {priors[c]}")
        for word in vocab:
            count = test_input.get(word, 0)
            if count > 0:
                print(f"P({word}|{c}) = {likelihood[c][word]}")
        print(f"Final Probability = {prob}")

    prediction = max(results, key=results.get)
    print("\nPredicted Class:", prediction)
    return prediction