# -*- coding: utf-8 -*-
"""DL Lab Assignment 10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1He7mfHZBaoTyybghg9V2_oxpUj3JQIlk

Name: Anushka Gupta
Class: CSAI-A TY
Batch: 3
Roll No.: 06
PRN: 12311317
Assignment 10
"""

# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# Load dataset
df = pd.read_csv('weather.csv')
df['date'] = pd.to_datetime(df['date'])
df.set_index('date', inplace=True)

# Select temperature column
data = df[['temperature']].values

# Normalize data
scaler = MinMaxScaler(feature_range=(0,1))
scaled_data = scaler.fit_transform(data)

# Create sequences
def create_dataset(dataset, time_step=10):
    X, Y = [], []
    for i in range(len(dataset) - time_step - 1):
        X.append(dataset[i:(i+time_step), 0])
        Y.append(dataset[i + time_step, 0])
    return np.array(X), np.array(Y)

time_step = 10
X, y = create_dataset(scaled_data, time_step)

# Reshape input for LSTM [samples, time steps, features]
X = X.reshape(X.shape[0], X.shape[1], 1)

# Train-test split
train_size = int(len(X)*0.8)
X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]

# Build LSTM model
model = Sequential()

model.add(LSTM(50, return_sequences=True, input_shape=(time_step,1)))
model.add(LSTM(50))
model.add(Dense(1))

model.compile(loss='mean_squared_error', optimizer='adam')

# Train model
model.fit(X_train, y_train, validation_data=(X_test,y_test),
          epochs=20, batch_size=32, verbose=1)

# Predictions
train_predict = model.predict(X_train)
test_predict = model.predict(X_test)

# Inverse scaling
train_predict = scaler.inverse_transform(train_predict)
test_predict = scaler.inverse_transform(test_predict)

# Plot results
plt.figure(figsize=(10,6))
plt.plot(df.index, data, label='Actual Data')
plt.plot(df.index[time_step+1:len(train_predict)+time_step+1],
         train_predict, label='Train Prediction')
plt.plot(df.index[len(train_predict)+time_step+1:len(data)],
         test_predict, label='Test Prediction')
plt.legend()
plt.title("Weather Prediction using LSTM")
plt.xlabel("Date")
plt.ylabel("Temperature")
plt.show()